# Generated by Django 5.2.16 on 2026-07-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proteinpathogenicityfeature',
            name='score',
            field=models.TextField(blank=True, null=True),
        ),
    ]
