# Generated by Django 5.2.16 on 2026-07-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_proteinpathogenicityfeature_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicMetadataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(db_index=True, max_length=120)),
                ('record_key', models.CharField(max_length=255)),
                ('sample_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('strain_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('source_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('payload', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'basic_metadata_records',
                'ordering': ['table_name', 'record_key'],
                'indexes': [models.Index(fields=['table_name', 'sample_id'], name='basic_metad_table_n_006a28_idx'), models.Index(fields=['table_name', 'strain_id'], name='basic_metad_table_n_62d73f_idx')],
                'constraints': [models.UniqueConstraint(fields=('table_name', 'record_key'), name='uniq_basic_metadata_record')],
            },
        ),
    ]
